### ISSUE TITLE
Bug: Library not showing books even though they are still on processed

### ISSUE THREAD

**Issue by raisingirl2024** [TortugaPower/BookPlayer#1354]
- OS Version: 18.7
 - App Version: Latest

My library suddenly decided to not show at least 1/3 of my books- even though going to the files in storage they are still there on the Processed folder. Artwork also disappeared for many of those that still showed. I updated iPhone to latest software and still same. Have had to erase my whole library as it was getting so frustrating. 
Then signed out and signed in again- and even though I have a Pro Membership I cannot see the extra app icons.

## Steps to reproduce the behavior
1. 
2. 
3.

**Comment by GianniCarlo** [comment]
@raisingirl2024 sorry about this, I'm still trying to catch the issue on the library list. Regarding the app icons, I've fixed this in v5.13.1 which Apple just approved (it's included in the changes in [this PR](https://github.com/TortugaPower/BookPlayer/pull/1352)). The update should be available shortly as it propagates in the AppStore

**Comment by raisingirl2024** [comment]
Thank you- the app icons are back now after the update. Library still not great. All the added artwork is completely gone and there are files doubled up.

**Comment by GianniCarlo** [comment]
@raisingirl2024 I can check and clean that up from my side, can you share with me the email you used for your profile? you can send it to my email if you'd like gcarlo89@hotmail.com or support@bookplayer.app
